my_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from accounts import views as accounts_views
from post import views as post_views

urlpatterns = [
    path('register/', accounts_views.register, name='register'),
    path('accounts/profile/', accounts_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
    path('user/<str:username>',
         post_views.UserPostListView.as_view(), name='user-post'),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    path('', include('post.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import (PostListView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    UserPostListView,
                    CategoryListView
                    )
from . import views

app_name = 'post'

urlpatterns = [
    path('post/create/', PostCreateView.as_view(), name='create'),
    path('category/<slug:slug>/', CategoryListView.as_view(),
         name='category'),
    path('search/', views.search_view, name='search'),
    path('', PostListView.as_view(), name='blog-home'),
    path('featured/', views.featured_view, name='featured'),
    path('<slug:slug>/', views.details, name='post-detail'),
    path('<slug:slug>/share', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', PostListView.as_view(), name='post-list-by-tag'),
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<slug:slug>/delete/', PostDeleteView.as_view(), name='post-delete'),

]

post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils.text import slugify
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField


class PostCategory(models.Model):
    cat_title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(blank=True)
    cat_desc = models.TextField()

    class Meta:
        verbose_name = 'postcategory'
        verbose_name_plural = 'postcategories'

    def __str__(self):
        return self.cat_title

    def get_absolute_url(self):
        return reverse('post:category', args=[self.slug])


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(null=True)
    content = RichTextUploadingField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    thumb = models.ImageField(blank=True, null=True, upload_to='images/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    featured = models.BooleanField(default=False)
    published = models.BooleanField(default=False)
    category = models.ForeignKey(
        PostCategory, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.content[0:120] + '...'

    def get_absolute_url(self):
        return reverse('post:post-detail', kwargs={'slug': self.slug})

    tags = TaggableManager()


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-date',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)


@receiver(pre_save, sender=Post)
def pre_save_slug(sender, **kwargs):
    slug = slugify(kwargs['instance'].title)
    kwargs['instance'].slug = slug

post/forms.py
from django import forms
from .models import Post, Comment


class PostEmailForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)


class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'thumb',
            'category',
        ]


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'name',
            'email',
            'body',
        ]


class SearchForm(forms.Form):
    query = forms.CharField(max_length=None)

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.mail import send_mail
from .models import Post, PostCategory, Comment
from .forms import PostModelForm, PostCommentForm, PostEmailForm, SearchForm
from taggit.models import Tag
from django.db.models import Count
from haystack.query import SearchQuerySet

# Create your views here.


def post_share(request, slug):
    post = get_object_or_404(Post, slug=slug, published=True)
    sent = False

    if request.method == 'POST':
        form = PostEmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you read "{}"'.format(
                cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(
                post.title, post_url, cd['name'], cd['comment'])
            send_mail(subject, message, 'neupytechng@gmail.com', [cd['to']])
            sent = True
    else:
        form = PostEmailForm()
    context = {
        'form': form,
        'post': post,
        'sent': sent,
        'title': 'Post Share'
    }
    return render(request, 'post/share.html', context)


class PostListView(ListView):
    tag_slug = None
    tag = None
    category_slug = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    model = Post
    queryset = Post.objects.filter(published=True)
    template_name = 'post/home.html'
    context_object_name = 'posts'
    ordering = ['-created_at']
    paginate_by = 20


class UserPostListView(ListView):
    model = Post
    template_name = 'post/user_post.html'
    context_object_name = 'posts'
    paginate_by = 20

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-created_at')


def details(request, slug):
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        comment_form = PostCommentForm(data=request.POST)
        if comment_form.is_valid():
            new_commment = comment_form.save(commit=False)
            new_commment.post = post
            new_commment.save()

    else:
        comment_form = PostCommentForm
    posts_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(
        tags__in=posts_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count(
        'tags')).order_by('-same_tags', '-published')[:4]

    context = {
        'title': 'Blog Details',
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
        'similar_posts': similar_posts
    }
    return render(request, 'post/post_detail.html', context)


class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'post/post_create.html'
    form_class = PostModelForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    template_name = 'post/post_create.html'
    queryset = Post.objects.all()
    form_class = PostModelForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Post

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

    def get_success_url(self):
        return reverse('post:blog-home')


def featured_view(request):
    featured_post = Post.objects.filter(featured=True)
    print(featured_post)
    context = {
        'featured_post': featured_post,
        'title': 'Featured Posts'
    }

    return render(request, 'post/home.html', context)


def search_view(request):
    search_form = SearchForm()
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            cd = search_form.cleaned_data
            results = SearchQuerySet().models(Post).filter(
                content=cd['query']).load_all()

            total_results = results.count()
        context = {
            'search_form': search_form,
            'total_results': total_results,
            'results': results,
            'cd': cd,
            'title': 'Search'
        }
        return render(request, 'post/search.html', context)
    return render(request, 'post/search.html', {'search_form': search_form})


class CategoryListView(ListView):
    model = Post
    template_name = 'post/category.html'
    context_object_name = 'posts'

    def get_queryset(self):
        self.category = get_object_or_404(
            PostCategory, slug=self.kwargs['slug'])
        return Post.objects.filter(category=self.category, published=True)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['category'] = self.category
        return data
    # model = Post
    # template_name = 'post/user_post.html'
    # context_object_name = 'posts'
    # paginate_by = 20

    # def get_queryset(self):
    #     category = get_object_or_404(Post, slug=self.kwargs.get('slug'))
    #     return Post.objects.filter(cat_title=category).order_by('-created_at')

post/templates/post/category.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-8">
  <h1 class="my-4">{{ category.cat_title }}</h1>
  {% if posts %}
  <!-- Blog Post -->
  {% for post in posts %}
  <div class="card my-4 p-4">
    <div class="row">
      <div class="col-lg-5">
        <div class="view overlay rounded z-depth-2 mb-lg-0 mb-4">
          <img class="img-fluid" src="{{ post.thumb.url }}" alt="Sample image" />
          <a href="{% url 'post:post-detail' post.slug %}">
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>
      </div>
      <div class="col-lg-7">
        <a href="#!" class="green-text">
          <h6 class="font-weight-bold mb-3">
            <a href="{% url 'post:category' post.category.slug %}">{{ post.category}}</a>
          </h6>
        </a>

        <h3 class="font-weight-bold mb-3">
          <strong>{{ post.title }}</strong>
        </h3>

        <p>{{ post.snippet | safe }}</p>

        <p>
          by
          <a href="{% url 'user-post' post.author.username %}"><strong>{{ post.author | capfirst }}</strong></a> on
          {{ post.created_at | date:"F d, Y" }}
        </p>

        <a href="{% url 'post:post-detail' post.slug %}" class="btn btn-success btn-md">Read more</a>
      </div>
    </div>

  </div>
  {% endfor %}
  {% else %}
  <h3 class="display-4">There are no posts in this category yet</h3>
  {% endif %}


  <!-- Pagination -->
  <ul class="pagination justify-content-center mb-4">
    <li class="page-item">
      <a class="page-link" href="#">&larr; Older</a>
    </li>
    <li class="page-item disabled">
      <a class="page-link" href="#">Newer &rarr;</a>
    </li>
  </ul>
</div>

{% endblock %}

post/templates/post/home.html
{% extends 'base.html' %}
{% block content %}



<div class="col-md-8">


  {% if posts %}
  {% for post in posts %}

  <section class="my-4">
    <div class="card p-4">
      <div class="row">
        <div class="col-lg-5">
          <div class="view overlay rounded z-depth-2 mb-lg-0 mb-4">
            <img class="img-fluid" src="{{ post.thumb.url }}" alt="Sample image" />
            <a href="{% url 'post:post-detail' post.slug %}">
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
        </div>
        <div class="col-lg-7">
          <a href="#!" class="green-text">
            <h6 class="font-weight-bold mb-3">
              <a href="{% url 'post:category' post.category.slug %}">{{ post.category}}</a>
            </h6>
          </a>

          <h3 class="font-weight-bold mb-3">
            <strong>{{ post.title }}</strong>
          </h3>

          <p>{{ post.snippet | safe }}</p>

          <p>
            by
            <a href="{% url 'user-post' post.author.username %}"><strong>{{ post.author | capfirst }}</strong></a> on
            {{ post.created_at | date:"F d, Y" }}
          </p>

          <a href="{% url 'post:post-detail' post.slug %}" class="btn btn-success btn-md">Read more</a>
        </div>
      </div>

    </div>
  </section>
  {% endfor %}
  {% else %}
  <h3 class="display-4">There are no posts yet</h3>
  {% endif %}

  <!-- Pagination -->
  <ul class="pagination justify-content-center mb-4">
    <li class="page-item">
      <a class="page-link" href="#">&larr; Older</a>
    </li>
    <li class="page-item disabled">
      <a class="page-link" href="#">Newer &rarr;</a>
    </li>
  </ul>
</div>

{% endblock %}

<div class="carousel-inner">
  {% if featured %}
  {% for post in posts|slice:":3" %}
  {% if forloop.first %}
  <div class="active item">
    {% else %}
    <div class="item">
      {% endif %}
      <label>{{ post.title }}</label>
      <div class="carousel-caption">
        <h3 class="h3-responsive">Light mask</h3>
        <p>First text</p>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
<div class="container"></div>
<div class="jumbotron mt-2">
  {% if featured %}
  {% for post in posts %}
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item">
        <img class="img-fluid" src="{{ post.thumb.url }}" alt="Sample image" />
        <h1>jumbotron</h1>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
</div>

post/templates/post/post_confirm_delete.html
{% extends 'base.html' %}



{% block content %}
<div class="col-md-8">
    <div class="row">

        <form method="POST" action="">{% csrf_token %}
            <fieldset class="form-group">
                <legend class="mb-4">New Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div>
                <button class="mb-3 btn btn-outline-danger" type="submit">Yes, delete</a></button>
                <button class="mb-3 btn btn-outline-info"><a
                        href="{% url 'blog:post-detail' post.slug %}">Cancel</a></button>
            </div>
        </form>

    </div>
</div>
{% endblock %}

post/templates/post/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<div class="col-md-8">

    <div class="card p-4 m-4">


        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
            <fieldset class="form-group">
                <legend class="mb-4">Add A New Post</legend>
                {{ form.media}}
                {{ form|crispy}}
            </fieldset>
            <button class="mb-3 btn btn-outline-info" type="submit">Post</button>
        </form>
    </div>

</div>
{% endblock %}

post/templates/post/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

<!-- Post Content Column -->
<div class="col-lg-8">

    <!-- Title -->
    <h1 class="mt-4">{{ post.title }}</h1>

    <!-- Author -->
    <p class="lead">by <a href="{% url 'user-post' post.author.username %}">{{post.author|capfirst}}</a></p>
    <hr>
    <!-- Date/Time -->
    <p>Posted on {{ post.created_at|date:"F d, Y" }}</p>
    <hr>
    <!-- Preview Image -->
    <img class="img-fluid rounded" src="{{ post.thumb.url }}" alt="">
    <hr>
    <!-- Post Content -->
    <p class="lead">{{ post.content|safe }}</p>
    <hr>

    <!-- Comments Form -->
    <div class="card my-4">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">

            {% if new_comment %}
            <h3>Your comment has been added</h3>
            {% else %}
            <h3>Add a new comment</h3>
            <form class="border border-light p-5" method="POST">{% csrf_token %}
                <div class="form-group">
                    {{ comment_form|crispy }}
                </div>
                <button type="submit" class="btn btn-primary">Add comment</button>
            </form>
            {% endif %}
        </div>
    </div>

    <!-- Single Comment -->
    {% for comment in comments %}
    <div class="media mb-4">

        <div class="media-body">
            <h5 class="mt-0">{{ comment.name.capitalize }}</h5>
            <p>{{ comment.body|linebreaks }}</p>
            <small>{{ comment.date }}</small>
        </div>
    </div>
    {% empty %}
    <p>Be the first to comment</p>
    {% endfor %}

    <div>
        {% for post in similar_posts %}
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        {% empty %}
        There are no similar posts
        {% endfor %}
    </div>
</div>

{% endblock %}

post/templates/post/search.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="col-md-8">

    {% if 'query' in request.GET %}
    <h3>Posts containing "{{ cd.query }}"</h3>
    <h4>Found {{ total_results }} result{{ total_results}}</h4>
    {% for result in results %}
    {% with post=result.object %}
    <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
    {{ post.content|truncatewords:5 }}
    {% endwith %}
    {% empty %}
    <p>There are no results for your query</p>
    {% endfor %}
    <p><a href="{% url 'post:search' %}">search again</a></p>
    {% else %}

    <form action="." method="GET">
        {{ search_form|crispy}}
        <input type="submit" value="Search">
    </form>
    {% endif %}

    <!-- <form action="." method="GET">
        {{ search_form|crispy}}
        <button class="btn btn-primary">Search</button>
        {% if query %}
        <h3>Results</h3>

        {% for result in page.object_list %}
        <p>
            <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
        </p>
        {% empty %}
        <p>No results found.</p>
        {% endfor %}
        {% endif %}
    </form> -->
</div>
{% endblock %}

post/templates/post/share.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div id="share" class="container">
    {% if sent %}
    <div class="bg-success">
        <h2>{{ post.title }} was successfully sent by email</h2>
    </div>
    {% else %}
    <h2>Share "{{ post.title }}" by email</h2>
    <form action="" method="POST">{% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Share Post">
    </form>
    {% endif %}
</div>

{% endblock %}

post/templates/post/user_post.html
{% extends 'base.html' %}


{% block content %}
<div class="col-md-8">

    <h1 class="my-4">Posts By <strong> {{ view.kwargs.username|capfirst }}</strong></h1>
    {% if posts %}
    <!-- Blog Post -->
    {% for post in posts %}
    <div class="card mb-4">
        <a href="{% url 'post:post-detail' post.slug %}">
            <img class="card-img-top" src="{{ post.thumb.url }}" alt="">
        </a>
        <div class="card-body">
            <h2 class="card-title">{{ post.title }}</h2>
            <p class="card-text">{{ post.snippet|safe }}</p>
            <a href="{% url 'post:post-detail' post.slug %}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
            Posted on {{ post.created_at|date:"F d, Y" }} by {{post.author|capfirst}}

        </div>
        <div class="card-footer text-muted"><i class="fas fa-tags mr-2"></i>
            {% for tag in post.tags.all %}
            <a href="{% url 'post:post-list-by-tag' tag.slug %}">
                {{ tag.name|capfirst }}</a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h3 class="display-4">There are no posts from this author yet</h3>
    {% endif %}


    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
        <li class="page-item">
            <a class="page-link" href="#">&larr; Older</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link" href="#">Newer &rarr;</a>
        </li>
    </ul>

</div>

{% endblock %}