my_blog/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from accounts import views as accounts_views
from post import views as post_views

urlpatterns = [
    path('register/', accounts_views.register, name='register'),
    path('accounts/profile/', accounts_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('admin/', admin.site.urls),
    path('user/<str:username>',
         post_views.UserPostListView.as_view(), name='user-post'),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    path('', include('post.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import (PostListView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    UserPostListView,
                    CategoryListView
                    )
from . import views

app_name = 'post'

urlpatterns = [
    path('post/create/', PostCreateView.as_view(), name='create'),
    path('category/<slug:slug>/', CategoryListView.as_view(),
         name='category'),
    path('search/', views.search_view, name='search'),
    path('', PostListView.as_view(), name='blog-home'),
    path('featured/', views.featured_view, name='featured'),
    path('<slug:slug>/', views.details, name='post-detail'),
    path('<slug:slug>/share', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', PostListView.as_view(), name='post-list-by-tag'),
    path('<slug:slug>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<slug:slug>/delete/', PostDeleteView.as_view(), name='post-delete'),

]

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <meta name="description" content="" />
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Roboto|Lato|Cabin|Open+Sans" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'font/roboto//Roboto-Light.woff2' %}">
  <script src="https://kit.fontawesome.com/14645c62d5.js"></script>
  <title>My Blog {{ title }}</title>
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'post:blog-home' %}">SOTS247</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              All Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for c in links %}
              <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.cat_title|capfirst }}</a>
              {% endfor %}
            </div>
          </li>

        </ul>
      </div>
    </div>
  </nav>

  <div class="container">

    <div class="row">

      {% block content %}
      {% endblock %}

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card my-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="form-group">
              {{ search_form }}
            </div>
          </div>
        </div>
        <!-- Categories Widget -->



        <div class="card my-4 sticky">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-sm-6">
                <ul class="list-unstyled mb-0">
                  {% for c in links %}
                  <li>
                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.cat_title|capfirst }}</a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new
            Bootstrap 4 card containers!
          </div>
        </div>
      </div>

    </div>
  </div>
  <footer class="py-5 bg-dark">

    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; SOTS247 {% now 'Y' %} </p>
    </div>
    <!-- /.container -->
  </footer>
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/popper.js' %}"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
  <script src="{% static 'js/mdb.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>